### ISSUE TITLE
Incorrect visuals during normal ending cutscene

### ISSUE THREAD

**Issue by Giftfox** [cave-story-randomizer/cave-story-randomizer#102]
If at least one dog is in the player's inventory when they complete a normal ending run, sand zone cutscenes will display a dog floating in midair. This is because the dog is piggybacking on the player, even though the player is currently invisible. This could likely be easily fixed by removing any dogs from the inventory when the normal ending begins.

**Comment by duncathan** [comment]
I think this can happen with curly in core too if you grab her with tow rope but don't drain her

**Comment by HapaxL** [comment]
#130 should fix the puppy side of the issue

**Comment by HapaxL** [comment]
no issue with curly, NPC is deleted upon entering the map during normal ending (event 1200)
