### ISSUE TITLE
Softlocks

### ISSUE THREAD

**Issue by duncathan** [cave-story-randomizer/cave-story-randomizer#106]
- [x] Bottom of outer wall without flight (can reset)
- [x] ~~Execution chamber no missiles (can reset, will not fix)~~
- [ ] Jenka's house no missiles
- [ ] Curly's house lv2 bubbler
- [ ] Jenka's house lv2 bubbler
- [x] Last Cave access does not ensure Plantation access

**Comment by HapaxL** [comment]
add: 
- [ ] Last Cave access does not ensure Plantation access
