### ISSUE TITLE
Non-customizable MyChar-related sprites

### ISSUE THREAD

**Issue by HapaxL** [cave-story-randomizer/cave-story-randomizer#126]
Some sprites (related to MyChar) cannot be added to MyChar and therefore cannot be changed easily even though it'd be nice if we could:
- drowning sprites (hardcoded to be using Caret and don't support Mimiga Mask)
- baby puppies (uses NpcSand, spriteboxes overlap with the Sky Dragon's so we cannot add both to MyChar)
- possibly more? (i mentioned mimiga mask and puppy icons in ItemImage but dunc said he'd rather keep them vanilla)

Possible solution:
- Paste sprites from a custom location in MyChar onto Caret/NpcSand during generation

**Comment by duncathan** [comment]
an ASM hack could be used to address the drowning sprites. in fact, something like that may already exist. non-freeware platforms will just have the regular unmodified sprites

**Comment by duncathan** [comment]
gonna go ahead and say we're not going to fix baby puppies at this time
