### ISSUE TITLE
Waterway side house sparkle entity misplacement

### ISSUE THREAD

**Issue by HapaxL** [cave-story-randomizer/cave-story-randomizer#131]
pixel house sparkly bug
pixel house sparkly bug
pixel house sparkly bug

**Comment by duncathan** [comment]
while we're at it, we should replace this with a debug cat like in reservoir

also: this might only be happening when entering with Curly on your back, I'm not sure

**Comment by HapaxL** [comment]
debug cat says "you find nothing of interest there" and does not teleport you
