### ISSUE TITLE
What game version?

### ISSUE THREAD

**Issue by Paelor** [cave-story-randomizer/cave-story-randomizer#172]
Hello, I didn't see what version(s) are supported with this randomizer.. is it for the original cave story or cave story+ or both? If cave story+ is supported are both GOG and Steam versions supported? Thanks in advance.

**Comment by Miepee** [comment]
This supports the original Freeware Cave Story, and as of 2.2.3 it also supports Cave Story Tweaked.
Unless you're a developer, you want to use [Randovania](https://github.com/randovania/randovania/releases) to play.
