### ISSUE TITLE
arthur's key on ma pignon with machine gun for flight sucks

### ISSUE THREAD

**Issue by duncathan** [cave-story-randomizer/cave-story-randomizer#26]
proposed fix: make balrog 1 give a ton of EXP, and fightable at any time after obtaining the silver locket - but only once

**Comment by HapaxL** [comment]
could you add an "experience" requirement for, say, bubbler as a weapon that can break blocks, machine gun as a means of flight, and automatically trigger that requirement when reaching arthur's teleporter the first time? that would prevent bubbler from appearing as a weapon in first cave AND machine gun from being the flight item when you need flight to get arthur's key, and you wouldn't need special checks or to edit the game too much

**Comment by duncathan** [comment]
i chose to do it like #28 because i wanted to add an incentive for fighting balrog 1, since otherwise there's no reason to ever fight him. bubbler as a weapon to break blocks has other issues such as a softlock in sand zone if you level down while fighting curly
