### ISSUE TITLE
can fall out of bounds in the Balcony map when trying to enter the Throne room

### ISSUE THREAD

**Issue by HapaxL** [cave-story-randomizer/cave-story-randomizer#36]
By going fast enough and being high enough when trying to enter the Throne room (think "using Booster 2.0 while being as high as you can without bonking against the top of the exit"), you can bypass the <TRA event and fall out of bounds.

**Comment by duncathan** [comment]
??? is this in vanilla

**Comment by HapaxL** [comment]
no idea, i'll try it out.
if it's not in vanilla i think it might be because the "screen flashing" event is still not finished by the time the player reaches past the transition trigger?

**Comment by duncathan** [comment]
that was my next guess yeah

**Comment by HapaxL** [comment]
not in vanilla
