### ISSUE TITLE
Screen keeps flashing in Balcony when going from and to the Throne room

### ISSUE THREAD

**Issue by HapaxL** [cave-story-randomizer/cave-story-randomizer#37]
When passing through the forcefield to the Throne room in Balcony, the screen flashes briefly before the forcefield vanishes. By leaving the map (for example entering the Throne room) then coming back, the screen will flash again when the player passes by that same spot even though the forcefield isn't there anymore.

**Comment by duncathan** [comment]
just needs a simple do not appear when flag ID is set on the HV trigger
